public enum State {
    READ_INSERTED_CARD,
    AUTHENTICATE_PIN,
    SELECT_TRANSACTION,
    DEPOSIT_CASH,
    INVALID_CASH_RETURNED,
    ENTER_WITHDRAWAL_AMOUNT,
    CASH_DISPENSED,
    DISPLAY_BALANCE,
    TRANSACT_AGAIN,
    EXIT,
    RETURN_CARD
}
